services:
  - type: web
    name: mern-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: mern-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DB_HOST
        fromDatabase:
          name: mern-mysql
          property: host
      - key: DB_USER
        fromDatabase:
          name: mern-mysql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mern-mysql
          property: password
      - key: DB_NAME
        value: school_management
      - key: SKIP_DB_INIT_DURING_BUILD
        value: "true"

databases:
  - name: mern-mysql
    type: mysql
    ipAllowList: []