services:
  - type: web
    name: mern-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: mern-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MYSQL_HOST
        value: ${mern-mysql.HOSTNAME}
      - key: MYSQL_USER
        value: ${mern-mysql.USERNAME}
      - key: MYSQL_PASSWORD
        value: ${mern-mysql.PASSWORD}
      - key: MYSQL_DATABASE
        value: school_management

databases:
  - name: mern-mysql
    type: database
    databaseType: mysql
    ipAllowList: []
